name: 'Project ACE clang tidy'
author: 'Guillem Torrente (tmguillem)'
description: 'Github Action that builds a ROS 2 package and executes clang tidy in it'
branding:
  icon: 'activity'  
  color: blue
inputs:
  version:
    description: 'Specify to use either clang-tidy 10 or 12'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}